// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9RWF3vcM9zvjvN_AgwWuJNsHvqnDJYt0',
    appId: '1:735698662838:web:3fe2bc3164eeec1e223d17',
    messagingSenderId: '735698662838',
    projectId: 'flash-chat-c8993',
    authDomain: 'flash-chat-c8993.firebaseapp.com',
    storageBucket: 'flash-chat-c8993.appspot.com',
    measurementId: 'G-XMT2PJP8EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMdWVvslHXaTVqB2u_el6u2MgG59j72GU',
    appId: '1:735698662838:android:6eb178cd1f6e681e223d17',
    messagingSenderId: '735698662838',
    projectId: 'flash-chat-c8993',
    storageBucket: 'flash-chat-c8993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJW0dO2IrNFcpKEpqNznADLRICR2okdw',
    appId: '1:735698662838:ios:df15960150123d2e223d17',
    messagingSenderId: '735698662838',
    projectId: 'flash-chat-c8993',
    storageBucket: 'flash-chat-c8993.appspot.com',
    iosClientId: '735698662838-7qepgkrb7a2l0r7sg0e1bntopukubdbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJW0dO2IrNFcpKEpqNznADLRICR2okdw',
    appId: '1:735698662838:ios:df15960150123d2e223d17',
    messagingSenderId: '735698662838',
    projectId: 'flash-chat-c8993',
    storageBucket: 'flash-chat-c8993.appspot.com',
    iosClientId: '735698662838-7qepgkrb7a2l0r7sg0e1bntopukubdbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlashChat',
  );
}
